config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web, at: '/sidekiq'
  mount Api::Route => '/api'

  health_check_routes

  root to: 'deploy_jobs#index'
  resources :deploy_jobs, only: %i[index show] do
    get :download, on: :member
  end

  get 'workflows', controller: :workflows, action: :index
  get 'latest_deployments', controller: :latest_deployments, action: :index
  get '*path', controller: 'application', action: 'render_404'
end

app/models/deploy_job.rb
class DeployJob
  include Mongoid::Document
  include Mongoid::Timestamps

  extend Enumerize

  enumerize :type, in: %i[run_task service scheduled_task]
  enumerize :status, in: %i[initial provisioning deploying success failure reserved_cancel cancel]
  enumerize :mode, in: %i[manual auto slack]

  field :id, type: String
  field :type, type: String
  field :status, type: String
  field :mode, type: String
  field :slack_user_id, type: String
  field :slack_user_name, type: String
  field :slack_timestamp, type: Float
  field :repository, type: String
  field :account, type: String
  field :branch, type: String
  field :tag, type: String
  field :alias, type: String
  field :commit_id, type: String
  field :cluster, type: String
  field :run_task, type: String
  field :override_container, type: String
  field :override_command, type: String
  field :service, type: String
  field :scheduled_task_rule, type: String
  field :scheduled_task_target, type: String
  field :logs, type: Array
  field :task_definition_arn, type: String
  field :task_arns, type: Array
  field :started_at, type: Time
  field :finished_at, type: Time
  field :docker_build_time, type: Float
  field :execution_time, type: Float
  field :deployment_tag, type: String

  validates :mode, :account, :repository, :cluster, presence: true
  validate :check_type

  def self.generate_id
    Time.now.utc.strftime('%Y%m%d-%H%M%S')
  end

  def label
    "build-#{id}"
  end

  def self.latest_deployments
    pipeline = [
      { '$sort' => { 'created_at': -1 } },
      { '$match' => { '$or': [
        { 'type': DeployJob.type.find_value(:service) },
        { 'type': DeployJob.type.find_value(:scheduled_task) }
      ] } },
      { '$match' => { 'status': 'success' } },
      { '$group' => {
        '_id' => {
          'cluster': '$cluster',
          'type': '$type',
          'service': '$service',
          'scheduled_task_rule': '$scheduled_task_rule',
          'scheduled_task_target': '$scheduled_task_target'
        },
        'id': { '$first' => '$_id' },
        'cluster': { '$first' => '$cluster' },
        'type': { '$first' => '$type' },
        'service': { '$first' => '$service' },
        'scheduled_task_rule': { '$first' => '$scheduled_task_rule' },
        'scheduled_task_target': { '$first' => '$scheduled_task_target' },
        'repository': { '$first' => '$repository' },
        'branch': { '$first' => '$branch' },
        'tag': { '$first' => '$tag' },
        'created_at': { '$first' => '$created_at' }
      } },
      { '$project' => { '_id': 0 } },
      { '$sort' => {
        'cluster' => 1,
        'type' => -1,
        'service' => 1,
        'scheduled_task_rule' => 1,
        'scheduled_task_target' => 1
      } }
    ]

    deploy_job = DeployJob.collection.aggregate(pipeline)

    results = {}
    deploy_job.each do |value|
      results[value[:cluster]] = [] if results[value[:cluster]].nil?
      results[value[:cluster]] << {
        id: value[:id],
        type: value[:type],
        service: value[:service],
        scheduled_task_rule: value[:scheduled_task_rule],
        scheduled_task_target: value[:scheduled_task_target],
        repository: value[:repository],
        branch: value[:branch],
        tag: value[:tag],
        created_at: value[:created_at].in_time_zone
      }
    end

    results
  end

  def self.delete_invalid_jobs
    one_day_ago = Time.now - 1.day
    deleted_count = DeployJob.where(:created_at.lt => one_day_ago, :status.in => %i[initial provisioning deploying]).delete_all

    logger.info("Deleted #{deleted_count} invalid jobs.")
  end

  def update_status_provisioning(commit_id)
    self.status = DeployJob.status.find_value(:provisioning).to_s
    self.started_at = Time.now.utc
    self.commit_id = commit_id
    save

    logger.info('Deploy status updated. [provisioning]')
  end

  def update_status_deploying
    self.status = DeployJob.status.find_value(:deploying).to_s
    save

    logger.info('Deploy status updated. [deploying]')
  end

  def update_status_complate(params = {})
    self.status = DeployJob.status.find_value(:success).to_s
    self.finished_at = Time.now.utc
    self.execution_time = finished_at.to_f - started_at.to_f
    self.task_arns = params[:task_arns] if params[:task_arns].present?
    self.task_definition_arn = params[:task_definition_arn] if params[:task_definition_arn].present?
    save

    logger.info('Deploy status updated. [complete]')
  end

  def update_status_failure
    self.status = DeployJob.status.find_value(:failure).to_s
    self.finished_at = Time.now.utc
    self.execution_time = finished_at.to_f - started_at.to_f if started_at.present?
    save

    logger.info('Deploy status updated. [failure]')
  end

  def update_status_reserved_cancel
    self.status = DeployJob.status.find_value(:reserved_cancel).to_s
    save

    logger.info('Deploy status updated. [reserved cancel]')
  end

  def update_status_cancel
    self.status = DeployJob.status.find_value(:cancel).to_s
    self.finished_at = Time.now.utc
    self.execution_time = finished_at.to_f - started_at.to_f
    save

    logger.info('Deploy status updated. [cancel]')
  end

  def finished
    return unless Settings.github.deployment_tag && branch.present?

    logger.info("Push tags to Git. [#{label}]")

    self.deployment_tag = label
    save

    code_manager = Genova::CodeManager::Git.new(
      repository,
      branch:,
      tag:,
      alias: self.alias,
      logger:
    )
    code_manager.release(deployment_tag, commit_id)

    logger.info('Deployment is complete.')
  end

  private

  def logger
    Genova::Logger::MongodbLogger.new(self)
  end

  def check_type
    errors[:base] << 'Please specify deploy type.' unless type.present?
  end
end

app/controllers/deploy_jobs_controller.rb
class DeployJobsController < ApplicationController
  def index
    @deploy_jobs = DeployJob.where(parse_conditions).order_by(id: 'desc').page(params[:page]).per(20)
  end

  def show
    @deploy_job = DeployJob.find(params[:id])

    render status: :not_found if @deploy_job.nil?
  end

  def download
    deploy_job = DeployJob.find(params[:id])
    return redirect_to root_path if deploy_job.nil?

    send_data(
      (deploy_job.logs || []).join("\n"),
      filename: "deployjob_#{deploy_job.id}.log",
      type: 'text/plain'
    )
  end

  private

  def parse_conditions
    conditions = {}

    # Dates are stored in ISODate and search is not implemented yet.
    if params[:keywords].present?
      pairs = params[:keywords].split(',')
      pairs.each do |pair|
        key, value = pair.split(':', 2)
        next if value.nil?

        conditions[key.strip.to_sym] = value.strip
      end
    end

    if params[:dates].present?
      dates = params[:dates].split(' - ')

      start_date = Date.strptime(dates[0], "%Y/%m/%d")&.beginning_of_day
      end_date = Date.strptime(dates[1], "%Y/%m/%d")&.end_of_day

      if start_date && end_date
        conditions[:created_at] = { '$gte': start_date, '$lte': end_date }
      end
    end

    conditions
  end
end

app/views/deploy_jobs/index.html.erb
<div class="container">
  <h2 class="title">Deploy jobs</h2>
  <form>
    <div class="columns">
      <div class="column is-7">
        <div class="control has-icons-left">
          <input class="input" type="text" name="keywords" placeholder="Example: cluster:production,status:success" value="<%= params[:keywords] %>">
          <span class="icon is-left">
            <i class="fa-solid fa-magnifying-glass"></i>
          </span>
        </div>
      </div>
      <div class="column is-4">
        <input type="date" name="dates">
      </div>
      <div class="column is-1">
        <input type="submit" value="Search" class="button">
      </div>
    </div>
  </form>
  <% if @deploy_jobs.size > 0 %>
    <table class="table is-fullwidth is-hoverable is-striped has-text-centered">
      <thead>
        <th>ID</th>
        <th>Status</th>
        <th>Repository</th>
        <th>Branch/Tag</th>
        <th>Commit</th>
        <th>Mode</th>
        <th>Type</th>
        <th>Cluster</th>
        <th>Created at</th>
      </thead>
      <tbody>
        <% @deploy_jobs.each do |deploy_job| %>
          <tr>
            <td><%= link_to(deploy_job.id, deploy_job_path(deploy_job.id)) %></td>
            <td>
              <% if deploy_job.status == 'success' %>
                <i class="fa fa-check-circle"></i>
              <% elsif ['initial', 'provisioning', 'deploying', 'reserved_cancel'].include?(deploy_job.status) %>
                <i class="fa fa-spinner fa-spin"></i>
              <% elsif deploy_job.status == 'failure' %>
                <i class="fa fa-exclamation-triangle"></i>
              <% elsif deploy_job.status == 'cancel' %>
                <i class="fa fa-times-circle"></i>
              <% end %>
              <%= deploy_job.status %>
            </td>
            <td><%= deploy_job.repository %></td>
            <td>
              <% if deploy_job.branch.present? %>
                <%= deploy_job.branch.truncate(20) %>
              <% else %>
                refs/tags/<%= deploy_job.tag.truncate(20) %>
              <% end %>
            </td>
            <td>
              <% if deploy_job.commit_id.present? %>
                <i class="fab fa-github"></i>
                <%= link_to(deploy_job.commit_id[0, 7], Genova::Github::Client.new(deploy_job.repository).build_commit_uri(deploy_job.commit_id)) %>
              <% end %>
            </td>
            <td><%= deploy_job.mode %></td>
            <td><%= type_tag(deploy_job.type).html_safe %></td>
            <td><%= deploy_job.cluster %></td>
            <td><%= deploy_job.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <nav class="pagination is-right" role="navigation">
      <ul class="pagination-list">
        <%= paginate @deploy_jobs %>
      </ul>
    </div>
  <% else %>
    <p>No data found.</p>
  <% end %>
</div>

app/views/deploy_jobs/latest.html.erb
<div class="container">
  <h2 class="title">Latest deploy</h2>
  <% if @deployments.size > 0 %>
    <% @deployments.each do |cluster, deployment| %>
      <h3><%= cluster %></h3>
      <% deployment.each_with_index do |service, i| %>
        <% if i == 0 || i % 3 == 0 %>
          <div class="columns">
        <% end %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
              <h4><%= service[:type] %></h4>
              <p class="title">
                <% if service[:service].present? %>
                  <%= service[:service] %>
                <% else %>
                  <%= service[:scheduled_task_rule] %>:<%= service[:scheduled_task_target] %>
                <% end %>
              </p>
              <dl class="subtitle">
                <% if service[:branch].present? %>
                  <dt>Branch</dt>
                  <dd><%= service[:branch] %></dd>
                <% else %>
                  <dt>Tag</dt>
                  <dd><%= service[:tag] %></dd>
                <% end %>
                <dt>Created at</dt>
                <dd><%= service[:created_at] %></dd>
              </dl>
            </div>
          </div>
        </div>
        <% if (i + 1) % 3 == 0 || deployment.size == i + 1 %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <p>Deployment does not exist.</p>
  <% end %>
</div>

app/views/deploy_jobs/show.html.erb
<div class="container">
  <h2 class="title">Deploy jobs: <%= params[:id] %></h2>

  <% if @deploy_job.present? %>
    <% github_client = Genova::Github::Client.new(@deploy_job.repository) %>
    <dl class="meta">
      <div class="columns">
        <dt class="column is-2">Status</dt>
        <dd class="column is-4">
          <% if @deploy_job.status == 'success' %>
            <i class="fa fa-check-circle"></i>
          <% elsif ['initial', 'provisioning', 'deploying', 'reserved_cancel'].include?(@deploy_job.status) %>
            <i class="fa fa-spinner fa-spin"></i>
          <% elsif @deploy_job.status == 'failure' %>
            <i class="fa fa-exclamation-triangle"></i>
          <% elsif @deploy_job.status == 'cancel' %>
            <i class="fa fa-times-circle"></i>
          <% end %>
          <%= @deploy_job.status %>
        </dd>
        <dt class="column is-2">Account</dt>
        <dd class="column is-4"><%= @deploy_job.account %></dd>
      </div>
      <div class="columns">
        <dt class="column is-2">Repository</dt>
        <dd class="column is-4">
          <i class="fab fa-github"></i>
          <%= link_to(@deploy_job.repository, github_client.build_repository_uri) %>
        </dd>
        <% if @deploy_job.branch.present? %>
          <dt class="column is-2">Branch</dt>
          <dd class="column is-4">
            <i class="fab fa-github"></i>
            <%= link_to(@deploy_job.branch, github_client.build_branch_uri(@deploy_job.branch)) %>
          </dd>
        <% else %>
            <dt class="column is-2">Tag</dt>
            <dd class="column is-4">
            <i class="fab fa-github"></i>
            <%= link_to(@deploy_job.tag, github_client.build_branch_uri(@deploy_job.tag)) %>
          </dd>
        <% end %>
      </div>
      <div class="columns">
        <dt class="column is-2">Commit</dt>
        <dd class="column is-4">
          <% if @deploy_job.commit_id.present? %>
            <i class="fab fa-github"></i>
            <%= link_to(@deploy_job.commit_id[0, 7], github_client.build_commit_uri(@deploy_job.commit_id)) %>
          <% end %>
        </dd>
        <% if @deploy_job.deployment_tag.present? %>
          <dt class="column is-2">Git tag</dt>
          <dd class="column is-4">
            <i class="fab fa-github"></i>
            <%= link_to(@deploy_job.deployment_tag, github_client.build_tag_uri(@deploy_job.deployment_tag)) %>
          </dd>
        <% end %>
      </div>
      <div class="columns">
        <dt class="column is-2">Mode</dt>
        <dd class="column is-4"><%= @deploy_job.mode %></dd>
        <dt class="column is-2">Type</dt>
        <dd class="column is-4"><%= type_tag(@deploy_job.type).html_safe %></dd>
      </div>
      <div class="columns">
        <dt class="column is-2">Cluster</dt>
        <dd class="column is-4"><%= @deploy_job.cluster %></dd`>
        <% if @deploy_job.service.present? %>
          <dt class="column is-2">Service</dt>
          <dd class="column is-4"><%= @deploy_job.service %></dd>
        <% end %>
      </div>
      <% if @deploy_job.type == DeployJob.type.find_value(:run_task) %>
        <div class="columns">
          <dt class="column is-2">Run task</dt>
          <dd class="column is-4"><%= @deploy_job.run_task %></dd>
          <% if @deploy_job.override_container.present? %>
            <dt class="column is-2">Override container / Override command</dt>
            <dd class="column is-4"><%= @deploy_job.override_container %> / <%= @deploy_job.override_command %></dd>
          <% end %>
        </div>
      <% end %>
      <% if @deploy_job.type == DeployJob.type.find_value(:scheduled_task) %>
        <div class="columns">
          <dt class="column is-2">Scheduled task rule</dt>
          <dd class="column is-4"><%= @deploy_job.scheduled_task_rule %></dd>
          <dt class="column is-2">Scheduled task target</dt>
          <dd class="column is-4"><%= @deploy_job.scheduled_task_target %></dd>
        </div>
      <% end %>
      <% if @deploy_job.mode == DeployJob.mode.find_value(:slack) %>
        <div class="columns">
          <dt class="column is-2">Slack user</dt>
          <dd class="column is-4"><%= @deploy_job.slack_user_name %></dd>
        </div>
      <% end %>
      <% if @deploy_job.task_definition_arn.present? %>
        <div class="columns">
          <dt class="column is-2">Task definition ARN</dt>
          <dd class="column is-10"><%= @deploy_job.task_definition_arn %></dd>
        </div>
      <% end %>
      <% if @deploy_job.task_arns.present? %>
        <div class="columns">
          <dt class="column is-2">Task ARNs</dt>
          <dd class="column is-10">
            <ul>
              <% @deploy_job.task_arns.each do |task_arn| %>
                <li><%= task_arn %></li>
              <% end %>
            </ul>
          </dd>
        </div>
      <% end %>
      <div class="columns">
        <dt class="column is-2">Created at</dt>
        <dd class="column is-4"><%= @deploy_job.created_at %></dd>
      </div>
      <div class="columns">
        <dt class="column is-2">Started at</dt>
        <dd class="column is-4"><%= @deploy_job.started_at %></dd>
        <dt class="column is-2">Finished at</dt>
        <dd class="column is-4"><%= @deploy_job.finished_at %></dd>
      </div>
      <div class="columns">
        <dt class="column is-2">Docker build time</dt>
        <dd class="column is-4">
          <% if @deploy_job.docker_build_time.present? %>
            <%= BigDecimal(@deploy_job.docker_build_time.to_s).floor(2).to_f %> sec
          <% end %>
        </dd>
        <dt class="column is-2">Execution time</dt>
        <dd class="column is-4">
          <% if @deploy_job.execution_time.present? %>
            <%= BigDecimal(@deploy_job.execution_time.to_s).floor(2).to_f %> sec
          <% end %>
        </dd>
      </div>
    </dl>

    <h3 class="title is-5">Logs</h3>
    <% if @deploy_job.logs.present? %>
      <div class="level-right">
        <%= button_to download_deploy_job_path, method: 'get', class: 'button is-small is-rounded' do %>
          <span class="icon is-small">
            <i class="fa-solid fa-cloud-arrow-down"></i>
          </span>
          <span>Download</span>
        <% end %>
      </div>
      <div class="logs">
        <% @deploy_job.logs.each do |log| %>
          <pre><%= log %></pre>
        <% end %>
      </div>
    <% else %>
      <p>Log does not exist.</p>
    <% end %>
  <% else %>
   <p>No data found.</p>
  <% end %>
</div>