config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web, at: '/sidekiq'
  mount Api::Route => '/api'

  health_check_routes

  root to: 'deploy_jobs#index'
  resources :deploy_jobs, only: %i[index show] do
    get :download, on: :member
  end

  get 'workflows', controller: :workflows, action: :index
  get 'latest_deployments', controller: :latest_deployments, action: :index
  get '*path', controller: 'application', action: 'render_404'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no" />
    <title>genova</title>
    <%= csrf_meta_tags %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to('genova', deploy_jobs_path, class: 'navbar-item') %>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to('Latest deployment', latest_deployments_path, class: 'navbar-item') %>
          <%= link_to('Workflow', workflows_path, class: 'navbar-item') %>
          <%= link_to('Sidekiq', '/sidekiq', class: 'navbar-item') %>
        </div>
      </div>
    </nav>

    <section class="section">
      <%= yield %>
    </section>

    <%= javascript_include_tag('/assets/javascripts/application') %>
  </body>
</html>